dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
dd:
  secure: BzEGXcRcAZVFpKG8r+20vF5e/R+o8GO0DnOZxuANlXtXonC77EoFcgFrcjXqEkPorh2NSshlPuIbtZFJy9poXIVZ+oKF6EWbkSaBM4Mhh0n2e2ftsVQ9NdP27Sx61N/4h/iumewT2+eX8Eri0nhhU/KNFAwhm9MZ9BX4tptSOC+Xyb5a05osu9FPv9InNzwyqNX36ecaTPZh/JAEeOz18SbbGcZE+1kiEUJXQuplVVvxD9a6JQNKwLaPojKCccE9fWHeGyNyx3GwUV0nNnenKMw2EpULhesQom2KzostdF5OVLXXQtCsR0/o5OPmsyDH5+SBvojBP621p/57J77FbU3R8JDjczCFufcYy0PqQGHxG72uIPgPTjU2kPdWlimvH2aeggogNSJBF5p4oorqEJgXAWUTRUbLikKhE5ZgegEO3lLFJN3IDfvT2ROd5X4wFwHhlKVWkbt8sQ/vnGQCAbc6keI3aqZl9hMbnr7+AN2kuERIMOF6pIBRdvBDg1R25h7Hzw8lGfx5yxuAaKtasWPn1HGE9grIDFHHTAPLVpcYHYb6oEi/O06WB6smbO2w75EEWORpiTyeDDTSEbD8ewnZRiirMUvgdpoom6CsUVGxpgV5XazYed+1kpxMFwknDredCtcRaHPrn5TW5ceHAhKMR0RwxgMznZQx+S+krHM=
